# Generated by Django 5.0.1 on 2024-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0003_genre_remove_movie_genre_remove_tvshow_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
