# Generated by Django 5.0.1 on 2024-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0004_alter_movie_description_alter_movie_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
