# Generated by Django 5.0.1 on 2024-02-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_alter_movie_id_alter_tvshow_id"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="movie",
        ),
        migrations.AddField(
            model_name="favorite",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
