# Generated by Django 5.0.1 on 2024-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0006_remove_favorite_movie_favorite_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tvshow",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Comedy", "Comedy"),
                    ("Drama", "Drama"),
                    ("Fantasy", "Fantasy"),
                ],
                default=("Action", "Action"),
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Comedy", "Comedy"),
                    ("Drama", "Drama"),
                    ("Fantasy", "Fantasy"),
                ],
                default=("Action", "Action"),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
