# Generated by Django 5.0.1 on 2024-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseapp",
            "0007_remove_tvshow_genres_remove_movie_genres_movie_genre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="genre",
            field=models.CharField(max_length=50),
        ),
    ]
