# Generated by Django 5.0.1 on 2024-02-09 05:52

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="country",
            field=django_countries.fields.CountryField(default="IN", max_length=2),
        ),
    ]
